# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_tool.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 931)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, -10, 41, 31))
        self.label_3.setObjectName("label_3")
        self.current_device_name = QtWidgets.QLabel(self.centralwidget)
        self.current_device_name.setGeometry(QtCore.QRect(60, 0, 131, 16))
        self.current_device_name.setText("")
        self.current_device_name.setObjectName("current_device_name")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 0, 31, 16))
        self.label_5.setObjectName("label_5")
        self.current_res = QtWidgets.QLabel(self.centralwidget)
        self.current_res.setGeometry(QtCore.QRect(250, 0, 91, 16))
        self.current_res.setText("")
        self.current_res.setObjectName("current_res")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 0, 31, 16))
        self.label_7.setObjectName("label_7")
        self.current_framerate = QtWidgets.QLabel(self.centralwidget)
        self.current_framerate.setGeometry(QtCore.QRect(410, 0, 71, 21))
        self.current_framerate.setText("")
        self.current_framerate.setObjectName("current_framerate")
        self.Videolabel = QtWidgets.QLabel(self.centralwidget)
        self.Videolabel.setGeometry(QtCore.QRect(190, 20, 761, 651))
        self.Videolabel.setText("")
        self.Videolabel.setObjectName("Videolabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label.setObjectName("label")
        self.CalibrateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CalibrateButton.setGeometry(QtCore.QRect(0, 120, 181, 23))
        self.CalibrateButton.setObjectName("CalibrateButton")
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setGeometry(QtCore.QRect(0, 150, 181, 23))
        self.DownloadButton.setObjectName("DownloadButton")
        self.snlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.snlineEdit.setGeometry(QtCore.QRect(70, 60, 113, 20))
        self.snlineEdit.setObjectName("snlineEdit")
        self.CaptureButton = QtWidgets.QPushButton(self.centralwidget)
        self.CaptureButton.setGeometry(QtCore.QRect(0, 90, 181, 23))
        self.CaptureButton.setObjectName("CaptureButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 23))
        self.menubar.setObjectName("menubar")
        self.menudddd = QtWidgets.QMenu(self.menubar)
        self.menudddd.setObjectName("menudddd")
        self.menuresolution = QtWidgets.QMenu(self.menubar)
        self.menuresolution.setObjectName("menuresolution")
        self.menuframemate = QtWidgets.QMenu(self.menubar)
        self.menuframemate.setObjectName("menuframemate")
        self.menudebug_camera = QtWidgets.QMenu(self.menubar)
        self.menudebug_camera.setObjectName("menudebug_camera")
        self.menubayer_rgb_mode = QtWidgets.QMenu(self.menubar)
        self.menubayer_rgb_mode.setObjectName("menubayer_rgb_mode")
        self.menuoption = QtWidgets.QMenu(self.menubar)
        self.menuoption.setObjectName("menuoption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCOLOR_BAYER_BG2BGR = QtWidgets.QAction(MainWindow)
        self.actionCOLOR_BAYER_BG2BGR.setObjectName("actionCOLOR_BAYER_BG2BGR")
        self.actionCOLOR_BAYER_GB2BGR = QtWidgets.QAction(MainWindow)
        self.actionCOLOR_BAYER_GB2BGR.setObjectName("actionCOLOR_BAYER_GB2BGR")
        self.actionCOLOR_BAYER_RG2BGR = QtWidgets.QAction(MainWindow)
        self.actionCOLOR_BAYER_RG2BGR.setObjectName("actionCOLOR_BAYER_RG2BGR")
        self.actionCOLOR_BAYER_GR2BGR = QtWidgets.QAction(MainWindow)
        self.actionCOLOR_BAYER_GR2BGR.setObjectName("actionCOLOR_BAYER_GR2BGR")
        self.actioncolor_bayer = QtWidgets.QAction(MainWindow)
        self.actioncolor_bayer.setObjectName("actioncolor_bayer")
        self.actioncaptureImage = QtWidgets.QAction(MainWindow)
        self.actioncaptureImage.setObjectName("actioncaptureImage")
        self.menubar.addAction(self.menudddd.menuAction())
        self.menubar.addAction(self.menuresolution.menuAction())
        self.menubar.addAction(self.menuframemate.menuAction())
        self.menubar.addAction(self.menudebug_camera.menuAction())
        self.menubar.addAction(self.menubayer_rgb_mode.menuAction())
        self.menubar.addAction(self.menuoption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "device:"))
        self.label_5.setText(_translate("MainWindow", "res:"))
        self.label_7.setText(_translate("MainWindow", "fps:"))
        self.label.setText(_translate("MainWindow", "Sn_number:"))
        self.CalibrateButton.setText(_translate("MainWindow", "calibrate"))
        self.DownloadButton.setText(_translate("MainWindow", "download"))
        self.CaptureButton.setText(_translate("MainWindow", "capture"))
        self.menudddd.setTitle(_translate("MainWindow", "devicename"))
        self.menuresolution.setTitle(_translate("MainWindow", "resolution"))
        self.menuframemate.setTitle(_translate("MainWindow", "framemate"))
        self.menudebug_camera.setTitle(_translate("MainWindow", "debug_camera"))
        self.menubayer_rgb_mode.setTitle(_translate("MainWindow", "bayer_rgb_mode"))
        self.menuoption.setTitle(_translate("MainWindow", "option"))
        self.actionCOLOR_BAYER_BG2BGR.setText(_translate("MainWindow", "COLOR_BAYER_BG2BGR"))
        self.actionCOLOR_BAYER_GB2BGR.setText(_translate("MainWindow", "COLOR_BAYER_GB2BGR"))
        self.actionCOLOR_BAYER_RG2BGR.setText(_translate("MainWindow", "COLOR_BAYER_RG2BGR"))
        self.actionCOLOR_BAYER_GR2BGR.setText(_translate("MainWindow", "COLOR_BAYER_GR2BGR"))
        self.actioncolor_bayer.setText(_translate("MainWindow", "color_bayer"))
        self.actioncaptureImage.setText(_translate("MainWindow", "captureImage"))
